### ISSUE TITLE
Can not work with Google Search Sidebar at the same time.

### ISSUE THREAD

**Issue by weal1312** [jmlntw/google-search-region#12]
前幾天更新以後，似乎無法和Google Search Sidebar這個UserCSS一同使用了，只能二擇一
兩個一起用的話，左方側欄不會出現區域切換的選項

**Comment by weal1312** [comment]
重新看了一下新的網頁結構，加入以下CSS可以暫時解決問題

    .hdtb-mn-cont > .hide-focus-ring{
      display: block !important;
      width: var(--user-sidebar-width) !important;
      min-width: var(--user-sidebar-width) !important;
      max-width: var(--user-sidebar-width) !important;
    }
    ul.gm-region-menu-dropdown{
      display: block;
      position: static;
      box-shadow: none;
    }

**Comment by mnghsn** [comment]
直接寫死 `display: block` 的話，在未使用 Google Search Sidebar 的情況下選單不能自動收合。看來還是要翻新重寫選單的部分。

**Comment by weal1312** [comment]
我是把CSS寫在Google Search Sidebar那邊，剛好裡面也有一塊註解是Third-Party Compatibility
這樣也不會有你說的影響動作的問題

**Comment by mnghsn** [comment]
Fixed in https://github.com/jmlntw/google-search-sidebar/releases/tag/v0.3.6.
